server:
  port: 6819
spring:
  application: Sample flyway Service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/basic-concept?characterEncoding=UTF-8
    username: root
    password: khanh123456
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
    out-of-order: true
    validate-on-migrate: false
